Add Husky, Prettier and ESLint
Algeps/admin-panel pull request #2
Opened 2022-09-30 19:08 UTC by Algeps

2022-10-07 13:18 UTC, Muslik requested changes
<img width="538" alt="Screenshot 2022-10-07 at 16 17 16" src="https://user-images.githubusercontent.com/15676404/194562997-c47891ab-08d6-4d3d-b12e-aee8eb832bf6.png">

react разметка должна быть с расширением jsx,
precommit hook не срабатывает

2022-10-09 19:35 UTC, Algeps commented
![image](https://user-images.githubusercontent.com/65846105/194776109-b29f5784-a622-4128-a3f9-373db18e1904.png)
У меня всё срабатывает. Если у вас после последнего коммита осталась проблема, то что это может быть?

2022-10-10 11:13 UTC, Muslik commented
https://www.npmjs.com/package/husky
Выполните первые шаги по установке.
Плюс замените useTabs на false и во всех файлах замените на пробелы (чтобы npm start не выдавал ошибку)
По умолчанию в js отступ - 2 пробела

2022-10-10 16:01 UTC, Algeps commented
Исправил все ошибки.

2022-10-10 18:37 UTC, Muslik commented
> Исправил все ошибки.

Отступы два пробела, а не 4.

2022-10-10 18:46 UTC, Muslik commented
Ну вы не проверяете то что вы сделали. Вот я склонил ваш репозиторий и все равно не работает. Удалил, установил заново и заработало. Теперь все ок. https://asciinema.org/a/gwT655UmpwZEV2TEfMBTL3nOP

Исправьте пробелы на 2.

2022-10-10 19:14 UTC, Algeps commented
Да, я действительно первый раз не проверял. Перед коммитом [Fix bugs with Prettier and Eslint](https://github.com/Algeps/admin-panel/pull/2/commits/53ad6b2db90283c47503a9b486fffeff092564a7) я скачал и проверил свои изменения. 
Спасибо за быстрый ответ.
Есть ещё какие-нибудь замечания?

2022-10-10 19:16 UTC, Muslik approved these changes

2022-10-10 19:18 UTC, merged