[2] Page header on mocks
Algeps/admin-panel pull request #3
Opened 2022-11-12 19:49 UTC by Algeps

2022-11-13 00:19 UTC, Muslik requested changes

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  colorBlue: 'color_blue',
color_blue -> colorBlue.
Везде исправьте. Используем camelCase

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Icon/Icon.jsx
> +export const Icon = ({ className, iconName, ...props }) => {
props не используется

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  text = '',
text заменяем на children

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  inInput = false,
props лишний

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  colorBlue: 'color_blue',
В других файлах в том числе

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +    [styles['color_clear-blue']]:
в самих классах тоже по хорошему везде camelCase юзать

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Input/Input.jsx
> +  const [value, setValue] = useState(initValue);
input должен быть глупым. Стейт будет у компонента который его использует

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Input/Input.jsx
> +        {isButton && <Icon iconName={'v_arrow'} className={iconButtonClass} />}
Передавайте props аля postfix в который будете передавать React node, либо делайте инпут с нуля для dropdown-а.
Делать пропс для одного специфичного кейса - неправильно.

```javascript
<Input postfix={<Icon name="v_arrow" />} />
```

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Input/Input.jsx
> +        {children}
У input-а не должно быть children-ов. Это одиночный тег. Не нужно в него что то вкладывать.

2022-11-13 00:19 UTC, Muslik commented on src/components/modules/Filter/Filter.jsx
> +            type='button'
Это должен быть рабочий dropdown. Который при выборе будет писать в инпуте выбранные статусы через запятую. Либо слово "Любой" если не выбрано ничего или выбраны все статусы

2022-11-13 00:19 UTC, Muslik commented on src/components/modules/Filter/Filter.jsx
> +              styles.data_registration,
Везде классы меняем на camelCase

2022-11-13 00:19 UTC, Muslik commented on src/components/shared/Button/Button.jsx
> +  buttonSizeType = ButtonSizeTypes.sizeBig,
зачем тут prefix button и postfix type )

просто size и просто color

2022-11-17 16:27 UTC, Muslik requested changes
Будет видео

2022-11-20 09:27 UTC, Algeps commented
*исправить Filter(конкретно DropDown, чтобы можно было выбирать из выпадающего списка)
*исправить компонент Input(применить стили по сразу умолчанию, перенести disabled в props и убрать константу isDisabled)
ещё чтобы Input не был подстроен специально под Dropdown
*исправить компонент Button (перенести Icon в props)

2022-11-22 23:05 UTC, Muslik approved these changes
Ok

2022-11-23 02:51 UTC, merged